### ISSUE TITLE
Package load and dependencies installation

### ISSUE THREAD

**Issue by dprymidis** [saezlab/MetaProViz#72]
![image](https://github.com/saezlab/MetaProViz/assets/63108890/8af7ef1c-c449-45c2-98ea-9cfbe4b5219c)

When I load the package now I get this everytime.  

Clusterprofiler is already installed. I think it cannot check if its installed because clusterprofiler is not cran but from bioconductor.

**Comment by dprymidis** [comment]
Marc informed me that when he installed MetaProViz the packages from bioconductor ,EnhancedVolcano and Clusterprofiler were not installed automatically and he had to istall them manually. I also had this issue when Itested this.

**Comment by ChristinaSchmidt1** [comment]
Thanks, in this case I will definetly add this information to the vignette. So the user is informed that this may happen and if this is the case that they shall manually install the package. 
I will also see if I can find what is the reason for this, so maybe its something we can prevent.

**Comment by ChristinaSchmidt1** [comment]
I have done some reading and one reason might be that the package ‘EnhancedVolcano’ is not available for the version of R you have installed. Could you double check if this may be the issue for you and Marc?

**Comment by dprymidis** [comment]
No, We talked with Marc to check it out but didnt.

**Comment by ChristinaSchmidt1** [comment]
I have now removed those dependencies as `usethis::use_package` can not import BiocManager packages. There are other functions like use_dev_package, but also here we can not import BiocManager packages. 
This afffects clusterProfiler and EnhancedVolcano. We can remove the dependency to clusterProfiler once we have added a helper function for the Fishers Exact test.
